server:
  port: 8080

spring:
  application:
    name: cvs-backend
  profiles:
    active: dev

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

cvs:
  security:
    jwt:
      issuer: "cvs"
      secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET"
      expire-seconds: 86400

