CREATE DATABASE IF NOT EXISTS CVS DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'root'@'localhost' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON CVS.* TO 'root'@'localhost';
FLUSH PRIVILEGES;

